FROM openjdk:25-slim
VOLUME /tmp
ARG JAVA_OPTS
ENV JAVA_OPTS=$JAVA_OPTS
COPY build/libs/Specnogram-0.0.1-SNAPSHOT.jar specnogram.jar
EXPOSE 8080
ENTRYPOINT exec java $JAVA_OPTS -jar specnogram.jar
# For Spring-Boot project, use the entrypoint below to reduce Tomcat startup time.
#ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar specnogram.jar
